#!/bin/bash

#SBATCH --gres=gpu:a100:2 --nodelist=g129
#SBATCH -p compute
#SBATCH -J CH
#SBATCH --cpus-per-task=10
#SBATCH --mem=30000
#SBATCH -t 1-23:59:59

## --nodelist=g126
# #####gpu:rtxa6000:4  gpu:a100:3 #SBATCH --nodelist=g123

source /home/cosuji/anaconda3/etc/profile.d/conda.sh
conda activate webnlg3

# # Edit this jobs for each task
# # pinecone.py, llama2.py, llama_langchain.py

python3 pinecone.py --model "gpt-3.5-turbo" \
                    --task "ordering" \
                    --data_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/data/deepnlg" \
                    --write_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/results"


## Mapping the outputs
# python3 mapping.py --previous_data "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/data/deepnlg" \
#                 --pipeline_data "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/results" \
#                 --previous_task "structuring" \
#                 --Gen_model "chatgpt"




