#!/bin/bash

#SBATCH --gres=gpu:rtx2080ti:1
#SBATCH -p compute
#SBATCH -J AIx_g4
#SBATCH -t 1-23:59:59


source /home/cosuji/anaconda3/etc/profile.d/conda.sh
conda activate webnlg

#Better
llama2_chat_7b="64d3f4921d6d9231813cca39" 
llama2_70b="65804f2f6ddc00433c216801"
gpt_3_5="640b517694bf816d35a59125" 
gpt4="6414bd3cd09663e9225130e8" 
gpt4_turbo="654a42a36eb5634a236f5eb1"
falcon_instruct="65519d57bf42e6037ab109d5"
bloom="6551ab17bf42e6037ab109e0"
##Good
llama2_7B="6543cb991f695e72028e9428"
Solar_10B="65b7baac1d5ea75105c14971"
cohere="653fe6f47157be43a42d5720"
gpt4_turbo="654a42a36eb5634a236f5eb1"

# # Edit this jobs for each task 
python3 ../chatgpt.py --model_id "$gpt4_turbo"\
		    	--model_path "gpt4_turbo" \
                   	--task "reg" \
                    	--data_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/data/deepnlg" \
                    	--write_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/results"

## Mapping the outputs
#python3 ../mapping.py --previous_data "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/data/deepnlg" \
                      #--pipeline_data "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/results" \
                      #--previous_task "structuring" \
                      #--Gen_model "gpt4_turbo"

# Surface Realization
#python3 ../realization.py --model "llama7b" \
                #--task "sr" \
                #--surface_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/data/deepnlg/input/sr/surfacevocab.json" \
                #--write_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/results"
                ### --data_path "/home/cosuji/spinning-storage/cosuji/NLG_Exp/webnlg/data/deepnlg" \
